/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cool_couplet_rtmvv_Aefh */

#ifndef _Included_cool_couplet_rtmvv_Aefh
#define _Included_cool_couplet_rtmvv_Aefh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cool_couplet_rtmvv_Aefh
 * Method:    myreaddir
 * Signature: (I)Lcool/couplet/rtmvv/Dirent;
 */
JNIEXPORT jobject JNICALL Java_cool_couplet_rtmvv_Aefh_myreaddir
  (JNIEnv *, jclass, jint);

/*
 * Class:     cool_couplet_rtmvv_Aefh
 * Method:    myreadcouplet
 * Signature: (I)Lcool/couplet/rtmvv/Dirent;
 */
JNIEXPORT jobject JNICALL Java_cool_couplet_rtmvv_Aefh_myreadcouplet
  (JNIEnv *, jclass, jint);

/*
 * Class:     cool_couplet_rtmvv_Aefh
 * Method:    myreaddir2
 * Signature: (I)Lcool/couplet/rtmvv/Dirent;
 */
JNIEXPORT jobject JNICALL Java_cool_couplet_rtmvv_Aefh_myreaddir2
  (JNIEnv *, jclass, jint);

/*
 * Class:     cool_couplet_rtmvv_Aefh
 * Method:    myseekdir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cool_couplet_rtmvv_Aefh_myseekdir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cool_couplet_rtmvv_Aefh
 * Method:    mygetcwd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cool_couplet_rtmvv_Aefh_mygetcwd
  (JNIEnv *, jclass);

/*
 * Class:     cool_couplet_rtmvv_Aefh
 * Method:    myrewinddir
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cool_couplet_rtmvv_Aefh_myrewinddir
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
